server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: 13379517860@163.com
    password: TZYrm36Vh4wd7Pgr
  redis:
    database: 0
    host: ${db.host}
    port: 6379
    password: 1234
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${db.host}:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 1234
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  data:
    mongodb:
      host: ${db.host}
      port: 27017
      database: emos
#      authentication-database: admin
#      username: admin
#      password:
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"

emos:
  code: HelloWorld
  jwt:
    #密钥
    secret: abc123456
    #令牌过期时间（天）
    expire: 5
    #令牌缓存时间（天数）
    cache-expire: 10
  face:
    createFaceModelUrl: http://${db.host}:3000/create_face_model
    checkinUrl: http://${db.host}:3000/checkin
  email:
    system: 1023369905@qq.com
  image-folder: D:/emos/image
wx:
  app-id: wxc75eaab9baa5a676
  app-secret: 3073a9a2df2c07c102d0e653859c2027